Require dpdgraph.dpdgraph.

Require LibLN.
Require Coq.Program.Equality.

Require Dot_definitions.
Require Dot_proofs_wellformed_store.
Require Dot_proofs_weakening.
Require Dot_proofs_some_lemmas.
Require Dot_proofs_has_member.
Require Dot_proofs_tight_bound_completeness.
Require Dot_proofs_substitution.
Require Dot_proofs_narrowing.
Require Dot_proofs_misc_inversions.
Require Dot_proofs_possible_types.
Require Dot_proofs_misc.
Require Dot_proofs_safety.

Set DependGraph File "orig_wo_defs.dpd".

Print FileDependGraph
(*Dot_definitions*)
Dot_proofs_wellformed_store
Dot_proofs_weakening
Dot_proofs_some_lemmas
Dot_proofs_has_member
Dot_proofs_tight_bound_completeness
Dot_proofs_substitution
Dot_proofs_narrowing
Dot_proofs_misc_inversions
Dot_proofs_possible_types
Dot_proofs_misc
Dot_proofs_safety
.

Set DependGraph File "orig_wo_defs_slem.dpd".

Print FileDependGraph
(*Dot_definitions*)
Dot_proofs_wellformed_store
Dot_proofs_weakening
(*Dot_proofs_some_lemmas*)
Dot_proofs_has_member
Dot_proofs_tight_bound_completeness
Dot_proofs_substitution
Dot_proofs_narrowing
Dot_proofs_misc_inversions
Dot_proofs_possible_types
Dot_proofs_misc
Dot_proofs_safety
.
